CREATE USER 'user'@'localhost' IDENTIFIED BY 'user';
CREATE USER 'user'@'%' IDENTIFIED BY 'user';

GRANT ALL ON *.* TO 'user'@'localhost';
GRANT ALL ON *.* TO 'user'@'%';

CREATE DATABASE textbook;

USE textbook;

-- -----------------------------------------------------
-- Table `textbook`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `textbook`.`book` (
  `idBooks` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Title` TEXT NULL DEFAULT NULL,
  `Author` TEXT NULL DEFAULT NULL,
  `ISBN` TEXT NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Vendor` TEXT NULL DEFAULT NULL,
  `Price` DOUBLE NULL DEFAULT NULL,
  `Type` TEXT NULL DEFAULT NULL,
  `ProductLink` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO `textbook`.`book` (`idBooks`, `Title`, `Author`, `ISBN`, `Description`, `Vendor`, `Price`, `Type`, `ProductLink`)
VALUES 
	('1', 'Essential Calculus- Early Transcendentals', 'James Stewart', ' 978-1133112280', 'This book is for instructors who think that most calculus textbooks are too long. In writing the book, James Stewart asked himself: What is essential for a three-semester calculus course for scientists and engineers? ', 'Amazon', '152.60', 'Hardcover', 'https://www.amazon.com/Essential-Calculus-Transcendentals-James-Stewart/dp/1133112285/ref=mt_hardcover?_encoding=UTF8&me='),
	('2', 'Essential Calculus- Early Transcendentals', 'James Stewart', ' 978-1133112280', 'This book is for instructors who think that most calculus textbooks are too long. In writing the book, James Stewart asked himself: What is essential for a three-semester calculus course for scientists and engineers? ', 'Barnes and Noble', '228.65', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600000769691&storeId=19058'),
	('3', 'Essential Calculus- Early Transcendentals', 'James Stewart', ' 978-1133112280', 'This book is for instructors who think that most calculus textbooks are too long. In writing the book, James Stewart asked himself: What is essential for a three-semester calculus course for scientists and engineers? ', 'Barnes and Noble', '86.99', 'Digital', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600000769691&storeId=19058'),
	('4', 'Essential Calculus- Early Transcendentals', 'James Stewart', ' 978-1133112280', 'This book is for instructors who think that most calculus textbooks are too long. In writing the book, James Stewart asked himself: What is essential for a three-semester calculus course for scientists and engineers? ', 'Amazon', '86.99', 'Digital', 'https://www.amazon.com/Essential-Calculus-Transcendentals-James-Stewart-ebook/dp/B00B63M08K/ref=mt_kindle?_encoding=UTF8&me='),
	('5', 'Vector Calculus', 'Jerrold E. Marsden', ' 978-1429215084', 'Vector Calculus helps students gain an intuitive and solid understanding of this important subject. The book\'s careful account is a contemporary balance between theory, application, and historical development, providing it\'s readers with an insight into how mathematics progresses and is in turn influenced by the natural world.', 'Amazon', '127.66', 'Hardcover', 'https://www.amazon.com/Vector-Calculus-Jerrold-E-Marsden/dp/1429215089/ref=mt_hardcover?_encoding=UTF8&me='),
	('6', 'Vector Calculus', 'Jerrold E. Marsden', ' 978-1429215084', 'Vector Calculus helps students gain an intuitive and solid understanding of this important subject. The book\'s careful account is a contemporary balance between theory, application, and historical development, providing it\'s readers with an insight into how mathematics progresses and is in turn influenced by the natural world.', 'Amazon', '67.99', 'Digital', 'https://www.amazon.com/Vector-Calculus-Jerrold-E-Marsden-ebook/dp/B00HQO0U9O/ref=mt_kindle?_encoding=UTF8&me='),
	('7', 'Vector Calculus', 'Jerrold E. Marsden', ' 978-1429215084', 'Vector Calculus helps students gain an intuitive and solid understanding of this important subject. The book\'s careful account is a contemporary balance between theory, application, and historical development, providing it\'s readers with an insight into how mathematics progresses and is in turn influenced by the natural world.', 'Barnes and Noble', '217.10', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/VECTOR_CALCULUS/BNCB_TextbookDetailView?sectionId=81470250&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1166834&productId=500007761588&sectionList=&booksAddedforSec=&fromTBList=true'),
	('8', 'Vector Calculus', 'Jerrold E. Marsden', ' 978-1429215084', 'Vector Calculus helps students gain an intuitive and solid understanding of this important subject. The book\'s careful account is a contemporary balance between theory, application, and historical development, providing it\'s readers with an insight into how mathematics progresses and is in turn influenced by the natural world.', 'Barnes and Noble', '135.99', 'Digital', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/VECTOR_CALCULUS/BNCB_TextbookDetailView?sectionId=81470250&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1166834&productId=500007761588&sectionList=&booksAddedforSec=&fromTBList=true'),
	('9', 'Linear Algebra and Its Applications', 'David C. Lay', ' 978-0321982384', 'With traditional linear algebra texts, the course is relatively easy for students during the early stages as material is presented in a familiar, concrete setting. However, when abstract concepts are introduced, students often hit a wall. Instructors seem to agree that certain concepts (such as linear independence, spanning, subspace, vector space, and linear transformations) are not easily understood and require time to assimilate.', 'Amazon', '123.62', 'Hardcover', 'https://www.amazon.com/Linear-Algebra-Its-Applications-5th/dp/032198238X/ref=mt_hardcover?_encoding=UTF8&me='),
	('10', 'Linear Algebra and Its Applications', 'David C. Lay', ' 978-0321982384', 'With traditional linear algebra texts, the course is relatively easy for students during the early stages as material is presented in a familiar, concrete setting. However, when abstract concepts are introduced, students often hit a wall. Instructors seem to agree that certain concepts (such as linear independence, spanning, subspace, vector space, and linear transformations) are not easily understood and require time to assimilate.', 'Amazon', '139.41', 'Loose Leaf', 'https://www.amazon.com/Linear-Algebra-Applications-MyMathLab-Pearson/dp/0321989929/ref=mt_looseleaf?_encoding=UTF8&me='),
	('11', 'Linear Algebra and Its Applications', 'David C. Lay', ' 978-0321982384', 'With traditional linear algebra texts, the course is relatively easy for students during the early stages as material is presented in a familiar, concrete setting. However, when abstract concepts are introduced, students often hit a wall. Instructors seem to agree that certain concepts (such as linear independence, spanning, subspace, vector space, and linear transformations) are not easily understood and require time to assimilate.', 'Amazon', '117.44', 'Digital', 'https://www.amazon.com/Linear-Algebra-Its-Applications-David-ebook/dp/B00XIHIO6E/ref=mt_kindle?_encoding=UTF8&me='),
	('12', 'Linear Algebra and Its Applications', 'David C. Lay', ' 978-0321982384', 'With traditional linear algebra texts, the course is relatively easy for students during the early stages as material is presented in a familiar, concrete setting. However, when abstract concepts are introduced, students often hit a wall. Instructors seem to agree that certain concepts (such as linear independence, spanning, subspace, vector space, and linear transformations) are not easily understood and require time to assimilate.', 'Barnes and Noble', '191.90', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/LINEAR_ALGEBRAITS_APPLTEXT/BNCB_TextbookDetailView?sectionId=81472337&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1530889&productId=500021514407&sectionList=&booksAddedforSec=&fromTBList=true'),
	('13', 'Linear Algebra and Its Applications', 'David C. Lay', ' 978-0321982384', 'With traditional linear algebra texts, the course is relatively easy for students during the early stages as material is presented in a familiar, concrete setting. However, when abstract concepts are introduced, students often hit a wall. Instructors seem to agree that certain concepts (such as linear independence, spanning, subspace, vector space, and linear transformations) are not easily understood and require time to assimilate.', 'Barnes and Noble', '125.99', 'Digital', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/LINEAR_ALGEBRAITS_APPLTEXT/BNCB_TextbookDetailView?sectionId=81472337&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1530889&productId=500021514407&sectionList=&booksAddedforSec=&fromTBList=true'),
	('14', 'Fundamentals of Differential Equations', 'R. Kent Nagle', ' 978-0321977069', ' Fundamentals of Differential Equations presents the basic theory of differential equations and offers a variety of modern applications in science and engineering. This flexible text allows instructors to adapt to various course emphases (theory, methodology, applications, and numerical methods) and to use commercially available computer software.', 'Amazon', '182.46', 'Hardcover', 'https://www.amazon.com/Fundamentals-Differential-Equations-Kent-Nagle/dp/0321977068/ref=mt_hardcover?_encoding=UTF8&me='),
	('15', 'Fundamentals of Differential Equations', 'R. Kent Nagle', ' 978-0321977069', ' Fundamentals of Differential Equations presents the basic theory of differential equations and offers a variety of modern applications in science and engineering. This flexible text allows instructors to adapt to various course emphases (theory, methodology, applications, and numerical methods) and to use commercially available computer software.', 'Amazon', '128.15', 'Loose Leaf', 'https://www.amazon.com/Fundamentals-Differential-Equations-Books-Carte/dp/0321977157/ref=mt_looseleaf?_encoding=UTF8&me='),
	('16', 'Fundamentals of Differential Equations', 'R. Kent Nagle', ' 978-0321977069', ' Fundamentals of Differential Equations presents the basic theory of differential equations and offers a variety of modern applications in science and engineering. This flexible text allows instructors to adapt to various course emphases (theory, methodology, applications, and numerical methods) and to use commercially available computer software.', 'Amazon', '121.74', 'Digital', 'https://www.amazon.com/Fundamentals-Differential-Equations-Kent-Nagle-ebook/dp/B01MTBH2CB/ref=mt_kindle?_encoding=UTF8&me='),
	('17', 'Fundamentals of Differential Equations', 'R. Kent Nagle', ' 978-0321977069', ' Fundamentals of Differential Equations presents the basic theory of differential equations and offers a variety of modern applications in science and engineering. This flexible text allows instructors to adapt to various course emphases (theory, methodology, applications, and numerical methods) and to use commercially available computer software.', 'Barnes and Noble', '186.95', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/FUNDOF_DIFFERENTIAL_EQUATIONS/BNCB_TextbookDetailView?sectionId=81472348&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1051314&productId=500001557210&sectionList=&booksAddedforSec=&fromTBList=true'),
	('18', 'Fundamentals of Differential Equations', 'R. Kent Nagle', ' 978-0321977069', ' Fundamentals of Differential Equations presents the basic theory of differential equations and offers a variety of modern applications in science and engineering. This flexible text allows instructors to adapt to various course emphases (theory, methodology, applications, and numerical methods) and to use commercially available computer software.', 'Barnes and Noble', '140.20', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/FUNDOF_DIFFERENTIAL_EQUATIONS/BNCB_TextbookDetailView?sectionId=81472348&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1051314&productId=500001557210&sectionList=&booksAddedforSec=&fromTBList=true'),
	('19', 'Geometry- Euclid and Beyond', 'Robin Hartshorne', ' 978-0387986500', 'This book offers a unique opportunity to understand the essence of one of the great thinkers of western civilization. A guided reading of Euclid\'s Elements leads to a critical discussion and rigorous modern treatment of Euclid\'s geometry and its more recent descendants, with complete proofs.', 'Amazon', '43.78', 'Hardcover', 'https://www.amazon.com/Geometry-Euclid-Beyond-Undergraduate-Mathematics/dp/0387986502/ref=mt_hardcover?_encoding=UTF8&me='),
	('20', 'Geometry- Euclid and Beyond', 'Robin Hartshorne', ' 978-0387986500', 'This book offers a unique opportunity to understand the essence of one of the great thinkers of western civilization. A guided reading of Euclid\'s Elements leads to a critical discussion and rigorous modern treatment of Euclid\'s geometry and its more recent descendants, with complete proofs.', 'Barnes and Noble', '48.70', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/GEOMETRYEUCLIDBEYOND/BNCB_TextbookDetailView?sectionId=81470264&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_466746&productId=500000344348&sectionList=&booksAddedforSec=&fromTBList=true'),
	('21', 'Web 101', 'Wendy G. Lehnert', ' 978-0321424679', 'As the Internet continues to develop as the central resource for entertainment, news, communication, and research, Web 101 continues to include all the tools readers need to acquire a foundational understanding of the online resources available today and how to take full advantage of the Web’s power.', 'Amazon', '161.20', 'Paperback', 'https://www.amazon.com/dp/0321424670/ref=olp_product_details?_encoding=UTF8&me='),
	('22', 'Web 101', 'Wendy G. Lehnert', ' 978-0321424679', 'As the Internet continues to develop as the central resource for entertainment, news, communication, and research, Web 101 continues to include all the tools readers need to acquire a foundational understanding of the online resources available today and how to take full advantage of the Web’s power.', 'Barnes and Noble', '147.45', 'Paperback', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/WEB_101/BNCB_TextbookDetailView?sectionId=81473710&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_783042&productId=500000804972&sectionList=&booksAddedforSec=&fromTBList=true'),
	('23', 'Probability and Statistics for Engineering and the Sciences', 'Jay L. Devore', ' 978-1305251809', 'Put statistical theories into practice with PROBABILITY AND STATISTICS FOR ENGINEERING AND THE SCIENCES, 9th Edition. Always a favorite with statistics students, this calculus-based text offers a comprehensive introduction to probability and statistics while demonstrating how professionals apply concepts, models, and methodologies in today\'s engineering and scientific careers.', 'Amazon', '159.54', 'Hardcover', 'https://www.amazon.com/Probability-Statistics-Engineering-Sciences-Devore/dp/1305251806/ref=mt_hardcover?_encoding=UTF8&me='),
	('24', 'Probability and Statistics for Engineering and the Sciences', 'Jay L. Devore', ' 978-1305251809', 'Put statistical theories into practice with PROBABILITY AND STATISTICS FOR ENGINEERING AND THE SCIENCES, 9th Edition. Always a favorite with statistics students, this calculus-based text offers a comprehensive introduction to probability and statistics while demonstrating how professionals apply concepts, models, and methodologies in today\'s engineering and scientific careers.', 'Amazon', '69.49', 'Digital', 'https://www.amazon.com/Probability-Statistics-Engineering-Sciences-Devore-ebook/dp/B00QXKGG0Y/ref=mt_kindle?_encoding=UTF8&me='),
	('25', 'Probability and Statistics for Engineering and the Sciences', 'Jay L. Devore', ' 978-1305251809', 'Put statistical theories into practice with PROBABILITY AND STATISTICS FOR ENGINEERING AND THE SCIENCES, 9th Edition. Always a favorite with statistics students, this calculus-based text offers a comprehensive introduction to probability and statistics while demonstrating how professionals apply concepts, models, and methodologies in today\'s engineering and scientific careers.', 'Barnes and Noble', '137.20', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/PROBABILITYSTATFENGRSCITEXT/BNCB_TextbookDetailView?sectionId=81476193&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1483977&productId=500018914480'),
	('26', 'Probability and Statistics for Engineering and the Sciences', 'Jay L. Devore', ' 978-1305251809', 'Put statistical theories into practice with PROBABILITY AND STATISTICS FOR ENGINEERING AND THE SCIENCES, 9th Edition. Always a favorite with statistics students, this calculus-based text offers a comprehensive introduction to probability and statistics while demonstrating how professionals apply concepts, models, and methodologies in today\'s engineering and scientific careers.', 'Barnes and Noble', '69.49', 'Digital', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/PROBABILITYSTATFENGRSCITEXT/BNCB_TextbookDetailView?sectionId=81476193&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1483977&productId=500018914480'),
	('27', 'A Second Course in Statistics- Regression Analysis', 'William Mendenhall', ' 978-0130223234', 'This reader-friendly book focuses on building linear statistical models and developing skills for implementing regression analysis in real-life situations. It includes applications for a range of fields including engineering, sociology, and psychology, as well as traditional business applications.', 'Amazon', '23.98', 'Used', 'https://www.amazon.com/Second-Course-Statistics-Regression-Analysis/dp/0321691695/ref=mt_hardcover?_encoding=UTF8&me='),
	('28', 'A Second Course in Statistics- Regression Analysis', 'William Mendenhall', ' 978-0130223234', 'This reader-friendly book focuses on building linear statistical models and developing skills for implementing regression analysis in real-life situations. It includes applications for a range of fields including engineering, sociology, and psychology, as well as traditional business applications.', 'Amazon', '126.99', 'Digital', 'https://www.amazon.com/Second-Course-Statistics-Regression-Analysis-ebook/dp/B005H8D8AY/ref=mt_kindle?_encoding=UTF8&me='),
	('29', 'A Second Course in Statistics- Regression Analysis', 'William Mendenhall', ' 978-0130223234', 'This reader-friendly book focuses on building linear statistical models and developing skills for implementing regression analysis in real-life situations. It includes applications for a range of fields including engineering, sociology, and psychology, as well as traditional business applications.', 'Barnes and Noble', '226.50', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/SECOND_CRSEIN_STATISTICSWCD/BNCB_TextbookDetailView?sectionId=81476198&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1052019&productId=500001553008'),
	('30', 'A Second Course in Statistics- Regression Analysis', 'William Mendenhall', ' 978-0130223234', 'This reader-friendly book focuses on building linear statistical models and developing skills for implementing regression analysis in real-life situations. It includes applications for a range of fields including engineering, sociology, and psychology, as well as traditional business applications.', 'Barnes and Noble', '169.90', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/SECOND_CRSEIN_STATISTICSWCD/BNCB_TextbookDetailView?sectionId=81476198&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1052019&productId=500001553008'),
	('31', 'A Second Course in Statistics- Regression Analysis', 'William Mendenhall', ' 978-0130223234', 'This reader-friendly book focuses on building linear statistical models and developing skills for implementing regression analysis in real-life situations. It includes applications for a range of fields including engineering, sociology, and psychology, as well as traditional business applications.', 'Barnes and Noble', '126.99', 'Digital', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/SECOND_CRSEIN_STATISTICSWCD/BNCB_TextbookDetailView?sectionId=81476198&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1052019&productId=500001553008'),
	('32', 'Linear Models with R', 'Julian J. Faraway', '978-1439887332', 'Part of the core of statistics, linear models are used to make predictions and explain the relationship between the response and the predictors. Understanding linear models is crucial to a broader competence in the practice of statistics.', 'Amazon', '64.98', 'Hardcover', 'https://www.amazon.com/Linear-Models-Chapman-Statistical-Science/dp/1439887330/ref=mt_hardcover?_encoding=UTF8&me='),
	('33', 'Linear Models with R', 'Julian J. Faraway', '978-1439887332', 'Part of the core of statistics, linear models are used to make predictions and explain the relationship between the response and the predictors. Understanding linear models is crucial to a broader competence in the practice of statistics.', 'Amazon', '76.80', 'Digital', 'https://www.amazon.com/Linear-Models-Chapman-Statistical-Science-ebook/dp/B00MMOIYXC/ref=mt_kindle?_encoding=UTF8&me='),
	('34', 'Linear Models with R', 'Julian J. Faraway', '978-1439887332', 'Part of the core of statistics, linear models are used to make predictions and explain the relationship between the response and the predictors. Understanding linear models is crucial to a broader competence in the practice of statistics.', 'Barnes and Noble', '96.00', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/LINEAR_MODELS_WITH_R/BNCB_TextbookDetailView?sectionId=81476200&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1502352&productId=500020601056'),
	('35', 'Linear Models with R', 'Julian J. Faraway', '978-1439887332', 'Part of the core of statistics, linear models are used to make predictions and explain the relationship between the response and the predictors. Understanding linear models is crucial to a broader competence in the practice of statistics.', 'Barnes and Noble', '89.95', 'Digital', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/LINEAR_MODELS_WITH_R/BNCB_TextbookDetailView?sectionId=81476200&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1502352&productId=500020601056'),
	('36', 'Linear Models with R', 'Julian J. Faraway', '978-1439887332', 'Part of the core of statistics, linear models are used to make predictions and explain the relationship between the response and the predictors. Understanding linear models is crucial to a broader competence in the practice of statistics.', 'Barnes and Noble', '72.00', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/LINEAR_MODELS_WITH_R/BNCB_TextbookDetailView?sectionId=81476200&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1502352&productId=500020601056'),
	('37', '21st Century Chemistry', 'Kimberley Waldron', '978-1936221394', 'Designed for chemistry and society classes, author Kimberley Waldron blends the central ideas of chemistry into stories that are relevant and familiar to non-science majors—from evaluating nutrition labels to understanding global warming and climate change.', 'Amazon', '72.82', 'Paperback', 'https://www.amazon.com/dp/193622139X/ref=olp_product_details?_encoding=UTF8&me='),
	('38', '21st Century Chemistry', 'Kimberley Waldron', '978-1936221394', 'Designed for chemistry and society classes, author Kimberley Waldron blends the central ideas of chemistry into stories that are relevant and familiar to non-science majors—from evaluating nutrition labels to understanding global warming and climate change.', 'Barnes and Noble', '110.00', 'Paperback', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/21ST_CENTURY_CHEMISTRY/BNCB_TextbookDetailView?sectionId=81475000&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_1532675&productId=500021514441'),
	('39', 'General, Organic, and Biological Chemistry- Structures of Life', 'Karen C. Timberlake', '978-0321967466', 'Designed to prepare students for health-related careers, General, Organic, and Biological Chemistry: Structures of Life breaks chemical concepts and problem solving into clear, manageable pieces, ensuring students follow along and stay motivated throughout their first, and often only, chemistry course.', 'Amazon', '184.99', 'Hardcover', 'https://www.amazon.com/General-Organic-Biological-Chemistry-Structures/dp/0321967461/ref=mt_hardcover?_encoding=UTF8&me='),
	('40', 'General, Organic, and Biological Chemistry- Structures of Life', 'Karen C. Timberlake', '978-0321967466', 'Designed to prepare students for health-related careers, General, Organic, and Biological Chemistry: Structures of Life breaks chemical concepts and problem solving into clear, manageable pieces, ensuring students follow along and stay motivated throughout their first, and often only, chemistry course.', 'Amazon', '171.06', 'Loose Leaf', 'https://www.amazon.com/General-Organic-Biological-Chemistry-Structures/dp/0133890805/ref=mt_looseleaf?_encoding=UTF8&me='),
	('41', 'General, Organic, and Biological Chemistry- Structures of Life', 'Karen C. Timberlake', '978-0321967466', 'Designed to prepare students for health-related careers, General, Organic, and Biological Chemistry: Structures of Life breaks chemical concepts and problem solving into clear, manageable pieces, ensuring students follow along and stay motivated throughout their first, and often only, chemistry course.', 'Amazon', '158.99', 'Digital', 'https://www.amazon.com/General-Organic-Biological-Chemistry-Structures-ebook/dp/B00XIHIE6Y/ref=mt_kindle?_encoding=UTF8&me='),
	('42', 'General, Organic, and Biological Chemistry- Structures of Life', 'Karen C. Timberlake', '978-0321967466', 'Designed to prepare students for health-related careers, General, Organic, and Biological Chemistry: Structures of Life breaks chemical concepts and problem solving into clear, manageable pieces, ensuring students follow along and stay motivated throughout their first, and often only, chemistry course.', 'Barnes and Noble', '215.80', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/GENERALORGANICBIOLLWMODCODE/BNCB_TextbookDetailView?sectionId=81475005&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=MBS_2031641&productId=500032467599'),
	('43', 'Financial Accounting', 'J. David Spiceland', '978-1259307959', 'Don’t you love those moments in your course when students are fully engaged? When the “Aha!”revelations are bursting like fireworks? David Spiceland Wayne Thomas and Don Herrmann have developed a unique set of materials based directly on their collective years in the classroom.', 'Amazon', '131.58', 'Digital', 'https://www.amazon.com/Financial-Accounting-J-David-Spiceland-ebook/dp/B0756N1VTZ/ref=mt_kindle?_encoding=UTF8&me='),
	('44', 'Financial Accounting', 'J. David Spiceland', '978-1259307959', 'Don’t you love those moments in your course when students are fully engaged? When the “Aha!”revelations are bursting like fireworks? David Spiceland Wayne Thomas and Don Herrmann have developed a unique set of materials based directly on their collective years in the classroom.', 'Amazon', '92.94', 'Hardcover', 'https://www.amazon.com/Financial-Accounting-J-David-Spiceland/dp/1259307956/ref=mt_hardcover?_encoding=UTF8&me='),
	('45', 'Financial Accounting', 'J. David Spiceland', '978-1259307959', 'Don’t you love those moments in your course when students are fully engaged? When the “Aha!”revelations are bursting like fireworks? David Spiceland Wayne Thomas and Don Herrmann have developed a unique set of materials based directly on their collective years in the classroom.', 'Amazon', '40.98', 'Used', 'https://www.amazon.com/Financial-Accounting-J-David-Spiceland/dp/1259307956/ref=mt_hardcover?_encoding=UTF8&me='),
	('46', 'Financial Accounting', 'J. David Spiceland', '978-1259307959', 'Don’t you love those moments in your course when students are fully engaged? When the “Aha!”revelations are bursting like fireworks? David Spiceland Wayne Thomas and Don Herrmann have developed a unique set of materials based directly on their collective years in the classroom.', 'Barnes and Noble', '200.00', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/FIN_ACCT_CUSTOM_F17_BUNDLE/BNCB_TextbookDetailView?sectionId=81473972&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=276_844008063&productId=550029710019'),
	('47', 'Financial Accounting', 'J. David Spiceland', '978-1259307959', 'Don’t you love those moments in your course when students are fully engaged? When the “Aha!”revelations are bursting like fireworks? David Spiceland Wayne Thomas and Don Herrmann have developed a unique set of materials based directly on their collective years in the classroom.', 'Barnes and Noble', '150.00', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/FIN_ACCT_CUSTOM_F17_BUNDLE/BNCB_TextbookDetailView?sectionId=81473972&item=Y&catalogId=10001&langId=-1&displayStoreId=19058&storeId=19058&partNumber=276_844008063&productId=550029710019'),
	('48', 'Advanced Calculus', 'Patrick M. Fitzpatrick', ' 978-0821847916', 'Advanced Calculus is intended as a text for courses that furnish the backbone of the student\'s undergraduate education in mathematical analysis. The goal is to rigorously present the fundamental concepts within the context of illuminating examples and stimulating exercises.', 'Amazon', '84.39', 'Hardcover', 'https://www.amazon.com/Advanced-Calculus-Applied-Undergraduate-Texts/dp/0821847910/ref=mt_hardcover?_encoding=UTF8&me='),
	('49', 'Advanced Calculus', 'Patrick M. Fitzpatrick', ' 978-0821847916', 'Advanced Calculus is intended as a text for courses that furnish the backbone of the student\'s undergraduate education in mathematical analysis. The goal is to rigorously present the fundamental concepts within the context of illuminating examples and stimulating exercises.', 'Amazon', '65.77', 'Used', 'https://www.amazon.com/Advanced-Calculus-Applied-Undergraduate-Texts/dp/0821847910/ref=mt_hardcover?_encoding=UTF8&me='),
	('50', 'Advanced Calculus', 'Patrick M. Fitzpatrick', ' 978-0821847916', 'Advanced Calculus is intended as a text for courses that furnish the backbone of the student\'s undergraduate education in mathematical analysis. The goal is to rigorously present the fundamental concepts within the context of illuminating examples and stimulating exercises.', 'Barnes and Noble', '87.00', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600000304177&storeId=19058'),
	('51', 'Advanced Calculus', 'Patrick M. Fitzpatrick', ' 978-0821847916', 'Advanced Calculus is intended as a text for courses that furnish the backbone of the student\'s undergraduate education in mathematical analysis. The goal is to rigorously present the fundamental concepts within the context of illuminating examples and stimulating exercises.', 'Barnes and Noble', '65.25', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600000304177&storeId=19058'),
	('52', 'Differential Equations and Linear Algebra', 'C. Henry Edwards', ' 978-0136054252', 'Acclaimed authors Edwards and Penney combine core topics in elementary differential equations with those concepts and methods of elementary linear algebra needed for a contemporary combined introduction to differential equations and linear algebra.', 'Amazon', '169.99', 'Hardcover', 'https://www.amazon.com/dp/0136054250/ref=olp_product_details?_encoding=UTF8&me='),
	('53', 'Differential Equations and Linear Algebra', 'C. Henry Edwards', ' 978-0136054252', 'Acclaimed authors Edwards and Penney combine core topics in elementary differential equations with those concepts and methods of elementary linear algebra needed for a contemporary combined introduction to differential equations and linear algebra.', 'Amazon', '50.00', 'Used', 'https://www.amazon.com/dp/0136054250/ref=olp_product_details?_encoding=UTF8&me='),
	('54', 'Differential Equations and Linear Algebra', 'C. Henry Edwards', ' 978-0136054252', 'Acclaimed authors Edwards and Penney combine core topics in elementary differential equations with those concepts and methods of elementary linear algebra needed for a contemporary combined introduction to differential equations and linear algebra.', 'Barnes and Noble', '186.95', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600000498114&storeId=19058'),
	('55', 'Differential Equations and Linear Algebra', 'C. Henry Edwards', ' 978-0136054252', 'Acclaimed authors Edwards and Penney combine core topics in elementary differential equations with those concepts and methods of elementary linear algebra needed for a contemporary combined introduction to differential equations and linear algebra.', 'Barnes and Noble', '140.20', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600000498114&storeId=19058'),
	('56', 'College Algebra Essentials', 'John W. Coburn', ' 978-0073519708', 'Applications are the hallmark of this series, along with student-friendly pedagogy and engaging examples and exercises. The integration of Connect Hosted by ALEKS, along with new lecture and exercise videos, provides students with the support they need to understand the key concepts of college algebra.', 'Amazon', '63.88', 'Hardcover', 'https://www.amazon.com/College-Algebra-Essentials-Coburn-Professor/dp/0073519707/ref=mt_hardcover?_encoding=UTF8&me='),
	('57', 'College Algebra Essentials', 'John W. Coburn', ' 978-0073519708', 'Applications are the hallmark of this series, along with student-friendly pedagogy and engaging examples and exercises. The integration of Connect Hosted by ALEKS, along with new lecture and exercise videos, provides students with the support they need to understand the key concepts of college algebra.', 'Amazon', '28.45', 'Used', 'https://www.amazon.com/College-Algebra-Essentials-Coburn-Professor/dp/0073519707/ref=mt_hardcover?_encoding=UTF8&me='),
	('58', 'College Algebra Essentials', 'John W. Coburn', ' 978-0073519708', 'Applications are the hallmark of this series, along with student-friendly pedagogy and engaging examples and exercises. The integration of Connect Hosted by ALEKS, along with new lecture and exercise videos, provides students with the support they need to understand the key concepts of college algebra.', 'Amazon', '71.19', 'Digital', 'https://www.amazon.com/College-Algebra-Essentials-John-Coburn-ebook/dp/B011PPRVUA/ref=mt_kindle?_encoding=UTF8&me='),
	('59', 'College Algebra Essentials', 'John W. Coburn', ' 978-0073519708', 'Applications are the hallmark of this series, along with student-friendly pedagogy and engaging examples and exercises. The integration of Connect Hosted by ALEKS, along with new lecture and exercise videos, provides students with the support they need to understand the key concepts of college algebra.', 'Barnes and Noble', '82.15', 'Digital', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600005378884&storeId=19058'),
	('60', 'College Algebra Essentials', 'John W. Coburn', ' 978-0073519708', 'Applications are the hallmark of this series, along with student-friendly pedagogy and engaging examples and exercises. The integration of Connect Hosted by ALEKS, along with new lecture and exercise videos, provides students with the support they need to understand the key concepts of college algebra.', 'Barnes and Noble', '121.45', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600005378884&storeId=19058'),
	('61', 'College Algebra Essentials', 'John W. Coburn', ' 978-0073519708', 'Applications are the hallmark of this series, along with student-friendly pedagogy and engaging examples and exercises. The integration of Connect Hosted by ALEKS, along with new lecture and exercise videos, provides students with the support they need to understand the key concepts of college algebra.', 'Barnes and Noble', '91.10', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600005378884&storeId=19058'),
	('62', 'Abstract Algebra- An Introduction', 'Thomas W. Hungerford', ' 978-1111569624', 'ABSTRACT ALGEBRA: AN INTRODUCTION is intended for a first undergraduate course in modern abstract algebra. Its flexible design makes it suitable for courses of various lengths and different levels of mathematical sophistication, ranging from a traditional abstract algebra course to one with a more applied flavor.', 'Amazon', '135.35', 'Hardcover', 'https://www.amazon.com/Abstract-Algebra-Introduction-Thomas-Hungerford/dp/1111569622/ref=mt_hardcover?_encoding=UTF8&me='),
	('63', 'Abstract Algebra- An Introduction', 'Thomas W. Hungerford', ' 978-1111569624', 'ABSTRACT ALGEBRA: AN INTRODUCTION is intended for a first undergraduate course in modern abstract algebra. Its flexible design makes it suitable for courses of various lengths and different levels of mathematical sophistication, ranging from a traditional abstract algebra course to one with a more applied flavor.', 'Amazon', '97.28', 'Used', 'https://www.amazon.com/Abstract-Algebra-Introduction-Thomas-Hungerford/dp/1111569622/ref=mt_hardcover?_encoding=UTF8&me='),
	('64', 'Abstract Algebra- An Introduction', 'Thomas W. Hungerford', ' 978-1111569624', 'ABSTRACT ALGEBRA: AN INTRODUCTION is intended for a first undergraduate course in modern abstract algebra. Its flexible design makes it suitable for courses of various lengths and different levels of mathematical sophistication, ranging from a traditional abstract algebra course to one with a more applied flavor.', 'Amazon', '69.49', 'Digital', 'https://www.amazon.com/Abstract-Algebra-Introduction-Thomas-Hungerford-ebook/dp/B00B6FAW2Y/ref=mt_kindle?_encoding=UTF8&me='),
	('65', 'Abstract Algebra- An Introduction', 'Thomas W. Hungerford', ' 978-1111569624', 'ABSTRACT ALGEBRA: AN INTRODUCTION is intended for a first undergraduate course in modern abstract algebra. Its flexible design makes it suitable for courses of various lengths and different levels of mathematical sophistication, ranging from a traditional abstract algebra course to one with a more applied flavor.', 'Barnes and Noble', '135.35', 'Hardcover', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600000673508&storeId=19058'),
	('66', 'Abstract Algebra- An Introduction', 'Thomas W. Hungerford', ' 978-1111569624', 'ABSTRACT ALGEBRA: AN INTRODUCTION is intended for a first undergraduate course in modern abstract algebra. Its flexible design makes it suitable for courses of various lengths and different levels of mathematical sophistication, ranging from a traditional abstract algebra course to one with a more applied flavor.', 'Barnes and Noble', '101.50', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600000673508&storeId=19058'),
	('67', 'Abstract Algebra- An Introduction', 'Thomas W. Hungerford', ' 978-1111569624', 'ABSTRACT ALGEBRA: AN INTRODUCTION is intended for a first undergraduate course in modern abstract algebra. Its flexible design makes it suitable for courses of various lengths and different levels of mathematical sophistication, ranging from a traditional abstract algebra course to one with a more applied flavor.', 'Barnes and Noble', '69.49', 'Digital', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600000673508&storeId=19058'),
	('68', 'Energy Economics', 'Peter M. Schwarz', '978-0415676786', 'With interest in topics such as climate change, energy security, and alternative energy sources being at an all-time high, the effects of today\'s decisions now rest on the shoulders of future generations. There are no easy answers to our energy issues, so costs and benefits must be considered when evaluating all energy alternatives; alongside that, prices must be right and need to reflect the full social costs to society of a given source of energy.', 'Amazon', '157.52', 'Hardcover', 'https://www.amazon.com/Economics-Routledge-Textbooks-Environmental-Agricultural/dp/0415676770/ref=mt_hardcover?_encoding=UTF8&me='),
	('69', 'Energy Economics', 'Peter M. Schwarz', '978-0415676786', 'With interest in topics such as climate change, energy security, and alternative energy sources being at an all-time high, the effects of today\'s decisions now rest on the shoulders of future generations. There are no easy answers to our energy issues, so costs and benefits must be considered when evaluating all energy alternatives; alongside that, prices must be right and need to reflect the full social costs to society of a given source of energy.', 'Amazon', '71.85', 'Paperback', 'https://www.amazon.com/Economics-Routledge-Textbooks-Environmental-Agricultural/dp/0415676789/ref=mt_paperback?_encoding=UTF8&me='),
	('70', 'Energy Economics', 'Peter M. Schwarz', '978-0415676786', 'With interest in topics such as climate change, energy security, and alternative energy sources being at an all-time high, the effects of today\'s decisions now rest on the shoulders of future generations. There are no easy answers to our energy issues, so costs and benefits must be considered when evaluating all energy alternatives; alongside that, prices must be right and need to reflect the full social costs to society of a given source of energy.', 'Amazon', '63.96', 'Digital', 'https://www.amazon.com/Economics-Routledge-Textbooks-Environmental-Agricultural-ebook/dp/B074SX2SV8/ref=mt_kindle?_encoding=UTF8&me='),
	('71', 'Energy Economics', 'Peter M. Schwarz', '978-0415676786', 'With interest in topics such as climate change, energy security, and alternative energy sources being at an all-time high, the effects of today\'s decisions now rest on the shoulders of future generations. There are no easy answers to our energy issues, so costs and benefits must be considered when evaluating all energy alternatives; alongside that, prices must be right and need to reflect the full social costs to society of a given source of energy.', 'Barnes and Noble', '79.95', 'Paperback', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=650015256406&storeId=19058'),
	('72', 'Energy Economics', 'Peter M. Schwarz', '978-0415676786', 'With interest in topics such as climate change, energy security, and alternative energy sources being at an all-time high, the effects of today\'s decisions now rest on the shoulders of future generations. There are no easy answers to our energy issues, so costs and benefits must be considered when evaluating all energy alternatives; alongside that, prices must be right and need to reflect the full social costs to society of a given source of energy.', 'Barnes and Noble', '59.95', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=650015256406&storeId=19058'),
	('73', 'The Thinkers Guide to Ethical Reasoning', 'Richard Paul', '978-0944583173', 'This guide provides insights into the nature of ethical reasoning, why it is so often flawed, and how to avoid those flaws. It lays out: the function of ethics, its main impediments, the social counterfeits of ethics, the elements of ethical reasoning, important ethical abilities and traits, the vocabulary of ethics, and the intellectual standards essential to the assessment of ethical reasoning.', 'Amazon', '19.29', 'Paperback', 'https://www.amazon.com/Thinkers-Guide-Ethical-Reasoning/dp/0944583172/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr='),
	('74', 'The Thinkers Guide to Ethical Reasoning', 'Richard Paul', '978-0944583173', 'This guide provides insights into the nature of ethical reasoning, why it is so often flawed, and how to avoid those flaws. It lays out: the function of ethics, its main impediments, the social counterfeits of ethics, the elements of ethical reasoning, important ethical abilities and traits, the vocabulary of ethics, and the intellectual standards essential to the assessment of ethical reasoning.', 'Amazon', '9.99', 'Digital', 'https://www.amazon.com/Thinkers-Guide-Ethical-Reasoning-Library-ebook/dp/B00OV5W6QG/ref=mt_kindle?_encoding=UTF8&me='),
	('75', 'The Thinkers Guide to Ethical Reasoning', 'Richard Paul', '978-0944583173', 'This guide provides insights into the nature of ethical reasoning, why it is so often flawed, and how to avoid those flaws. It lays out: the function of ethics, its main impediments, the social counterfeits of ethics, the elements of ethical reasoning, important ethical abilities and traits, the vocabulary of ethics, and the intellectual standards essential to the assessment of ethical reasoning.', 'Barnes and Noble', '18.30', 'Paperback', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600004248102&storeId=19058'),
	('76', 'The Thinkers Guide to Ethical Reasoning', 'Richard Paul', '978-0944583173', 'This guide provides insights into the nature of ethical reasoning, why it is so often flawed, and how to avoid those flaws. It lays out: the function of ethics, its main impediments, the social counterfeits of ethics, the elements of ethical reasoning, important ethical abilities and traits, the vocabulary of ethics, and the intellectual standards essential to the assessment of ethical reasoning.', 'Barnes and Noble', '13.75', 'Used', 'http://uncc.bncollege.com/webapp/wcs/stores/servlet/BNCB_TextbookDetailView?catalogId=10001&item=N&langId=-1&productId=600004248102&storeId=19058');

